ElmanhagPlatform/Models/Lecture.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ElmanhagPlatform.Models
{
    public class Lecture
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }

        [ForeignKey("CourseId")]
        public int CourseId { get; set; }
        public Course Course { get; set; }

        public ICollection<Video> Videos { get; set; }
        public ICollection<PFile> PFiles { get; set; }
        public ICollection<Exam> Exams{ get; set; } 

        public ICollection<Card> Cards{ get; set; }

    }
}

ElmanhagPlatform/Controllers/LectureController.cs
using ElmanhagPlatform.Data;
using ElmanhagPlatform.Models;
using ElmanhagPlatform.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ElmanhagPlatform.Controllers
{
    public class LectureController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IEmailProvider _emailProvider;

        public LectureController(AppDbContext context, IWebHostEnvironment hostingEnvironment
            , UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager,
            IEmailProvider emailProvider)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailProvider = emailProvider;
        }
        public async Task<IActionResult> Index(int id)
        {
            if (User.IsInRole("Teacher"))
            {
                if (HttpContext.Session.GetString("created") != null)
                {
                    ViewBag.created = true;
                    HttpContext.Session.Remove("created");
                }
                if (HttpContext.Session.GetString("updated") != null)
                {
                    ViewBag.updated = true;
                    HttpContext.Session.Remove("updated");
                }
                if (HttpContext.Session.GetString("deleted") != null)
                {
                    ViewBag.deleted = true;
                    HttpContext.Session.Remove("deleted");
                }

                var teacherId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                if (teacherId == null )
                {
                    return RedirectToAction("Index", "Home");
                }

                ViewBag.course = await _context.Courses.FindAsync(id);

                var Lec = await _context.Lectures.Where(u => u.CourseId == id && u.Course.TeacherId == teacherId).ToListAsync();
                
                ViewBag.CoursId = id;
                return View(Lec);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Create(int id, string? returnUrl = null)
        {
            if (User.IsInRole("Teacher"))
            {
                ViewData["ReturnUrl"] = returnUrl;

                ViewBag.course = await _context.Courses.FindAsync(id);
                
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( int id, Lecture model, string? returnUrl = null)
        {
            if (User.IsInRole("Teacher"))
            {
                ViewData["ReturnUrl"] = returnUrl;
                try
                {
                    var teacherId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                    if (teacherId == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    var Teacher = await _context.ApplicationUsers.FindAsync(teacherId);

                    var course = await _context.Courses.FindAsync(id);
                    if (course == null)
                    {
                        return RedirectToAction("Index", "Course");
                    }

                    if(course.TeacherId != teacherId)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    Lecture lec = new()
                    {
                        Name = model.Name,
                        Content = model.Content,
                        CourseId = id,
                    };

                    course.UpdateDate = DateOnly.FromDateTime(DateTime.Now);

                    _context.Update(course);
                    _context.Lectures.Add(lec);
                    await _context.SaveChangesAsync();

                    HttpContext.Session.SetString("created", "true");
                    return RedirectToAction("Index", new { id = course.Id });
                }
                catch
                {
                    return View(model);
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (User.IsInRole("Teacher"))
            {
                var lec = await _context.Lectures.FindAsync(id);

                var course = await _context.Courses.FindAsync(lec.CourseId);
                ViewBag.course = course;
                lec = new Lecture

                {
                    Id = id,
                    Name = lec.Name,
                    Content = lec.Content,
                    CourseId = course.Id,
                };
                return View(lec);
            }

            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Lecture courseForm)
        {
            if (User.IsInRole("Teacher"))
            {
                try
                {
                    var lec = await _context.Lectures.FindAsync(id);
                    if (lec == null)
                    {
                        return RedirectToAction("Index", "Course");
                    }

                    var course = await _context.Courses.FindAsync(lec.CourseId);
                    if (course == null)
                    {
                        return RedirectToAction("Index", "Course");
                    }

                    var teacherId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                    if (teacherId == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    if (course.TeacherId != teacherId)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    lec.Name = courseForm.Name;
                    lec.Content = courseForm.Content;

                    course.UpdateDate = DateOnly.FromDateTime(DateTime.Now);

                    _context.Update(course);
                    _context.Update(lec);
                    await _context.SaveChangesAsync();
                    HttpContext.Session.SetString("updated", "true");
                    return RedirectToAction("Index", new { id = course.Id });
                }
                catch
                {
                    var lec = await _context.Lectures.FindAsync(id);
                    if (lec == null)
                    {
                        return RedirectToAction("Index", "Course");
                    }

                    var course = await _context.Courses.FindAsync(lec.CourseId);
                    if (course == null)
                    {
                        return RedirectToAction("Index", "Course");
                    }

                    return RedirectToAction("Index", "Course");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (User.IsInRole("Teacher"))
            {
                if (id == null)
                {
                    return NotFound();
                }

                var lec = await _context.Lectures.FindAsync(id);

                var teacherId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                if (teacherId == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var Teacher = await _context.ApplicationUsers.FindAsync(teacherId);
                var course = await _context.Courses.FindAsync(lec.CourseId);
                if (course.TeacherId != teacherId)
                {
                    return RedirectToAction("Index", "Home");
                }

                var cards = await _context.Cards.Where(x => x.LectureId == lec.Id).ToListAsync();

                _context.Cards.RemoveRange(cards);

                _context.Lectures.Remove(lec);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("deleted", "true");
                return RedirectToAction("Index", new { id = lec.CourseId });
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

    }
}

ElmanhagPlatform/Views/Lecture/Create.cshtml
@using ElmanhagPlatform.Models;
@model Lecture

@{
    ViewData["Title"] = "Login Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .form-container {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .form-group {
            flex: 1 1 60%;
            min-width: 225px;
        }

        media (max-width: 768px) {
            .form-container{
                flex-direction: column;
            }
        }

        .hire-info {
            display: flex;
            justify-content: center;
            align-items: center;
            height: auto;
            padding: 20px;
            margin: 0;
            box-sizing: border-box;
        }

        .container {
            margin: 0 auto;
            padding: 0;
            overflow: hidden;
        }

        .hire-info form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            /* color: #ff9933; */
            text-align: center;
            margin-bottom: 20px;
        }

        .btn-h {
            /* background-color: #ff9933; */
            color: #333;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 20px;
        }

            .btn-h:hover {
                /* background-color: #ff9933; */
            }
    </style>
</head>

@section Styles {
    <link rel="stylesheet" type="text/css" href="~/lib/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="~/lib/table/datatable/dt-global_style.css">
    <link href="~/lib/toaster/toaster.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMvdL1eFiFmF5wN3K3jVrGzX+gY98/rFO7tB2kc" crossorigin="anonymous">
}
<body>
    <div id="contact" class="hire">
        <div class="container">
            <div class="hire-details">
                <h1 class="text-primary">اضافة محاضرة لكورس @ViewBag.course.Name</h1>
                <div class="hire-info">
                    <form id="account" method="post" asp-action="Create" asp-controller="Lecture" enctype="multipart/form-data" asp-route-returnurl="@ViewData["ReturnUrl"]">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-container">
                            <div class="form-group">
                                <input asp-for="Name" autocomplete="on" aria-required="true" required type="text" class="form-control" placeholder="اسم المحاضرة" onfocus="this.placeholder = ''" onblur="this.placeholder ='اسم المحاضرة'">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <textarea asp-for="Content" autocomplete="on" aria-required="true" required type="text" class="form-control" placeholder="محتوى المحاضرة" onfocus="this.placeholder = ''" onblur="this.placeholder ='محتوى المحاضرة'"></textarea>
                                <span asp-validation-for="Content" class="text-danger"></span>
                            </div>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3" role="alert"></div>

                        <div class="form-layout-footer mg-t-30 text-center">
                            <button id="login-submit" type="submit" class="btn-1 btn-h btn btn-primary"><i class="fas fa-plus"></i> اضافة</button>
                            <a asp-controller="Lecture" asp-action="Index" asp-route-id="@ViewBag.course.Id" class="btn-1 btn-h btn btn-primary">
                                <i class="fas fa-arrow-left"></i> رجوع
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

ElmanhagPlatform/Views/Lecture/Edit.cshtml
@using ElmanhagPlatform.Models;
@model Lecture

@{
    ViewData["Title"] = "Login Page";
}
<header>
    <style>
        .form-container {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }

        .form-group {
            flex: 1 1 60%;
            min-width: 225px;
        }

        media (max-width: 768px) {
            .form-container {
                flex-direction: column;
            }
        }

        .hire-info {
            display: flex;
            justify-content: center;
            align-items: center;
            height: auto;
            padding: 20px;
            margin: 0;
            box-sizing: border-box;
        }

        .container {
            margin: 0 auto;
            padding: 0;
            overflow: hidden;
        }

        .hire-info form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            /* color: #ff9933; */
            text-align: center;
            margin-bottom: 20px;
        }

        .btn-h {
            /* background-color: #ff9933; */
            color: #333;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 20px;
        }

            .btn-h:hover {
                /* background-color: #ff9933; */
            }
    </style>
</header>

<div id="contact" class="hire">
    <div class="container">
        <div class="hire-details">
            <h1 class="text-primary">تعديل بيانات محاضرة كورس @ViewBag.course.Name</h1>
            <div class="hire-info">
                <form id="account" method="post" asp-action="Edit" asp-controller="Lecture" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-container">
                        <div class="form-group">
                            <input asp-for="Name" autocomplete="on" aria-required="true" type="text" class="form-control" placeholder="اسم المحاضرة" onfocus="this.placeholder = ''" onblur="this.placeholder ='اسم المحاضرة'">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Content" autocomplete="on" aria-required="true" type="text" class="form-control" placeholder="محتوى المحاضرة" onfocus="this.placeholder = ''" onblur="this.placeholder ='محتوى المحاضرة'"></textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                    </div>

                    <div asp-validation-summary="ModelOnly" class="text-danger mb-3" role="alert"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-layout-footer mg-t-30 text-center">
                        <button type="submit" class="btn-1 btn-h btn btn-primary">
                            <i class="fas fa-save"></i> حفظ
                        </button>
                        <a asp-controller="Lecture" asp-action="Index" asp-route-id="@ViewBag.course.Id" class="btn-1 btn-h btn btn-primary">
                            <i class="fas fa-arrow-left"></i> رجوع
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}