ElmanhagPlatform/Controllers/StudentController.cs
using ElmanhagPlatform.Data;
using ElmanhagPlatform.Models;
using ElmanhagPlatform.Utility;
using ElmanhagPlatform.ViewModels.StudentVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ElmanhagPlatform.Controllers
{
    public class StudentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public StudentController(AppDbContext context, IWebHostEnvironment hostingEnvironment
            , UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Create(string? returnUrl = null)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                ViewData["ReturnUrl"] = returnUrl;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateStudentVM model, IFormFile Image, string? returnUrl = null)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                ViewData["ReturnUrl"] = returnUrl;
                if (ModelState.IsValid)
                {
                    ApplicationUser user = new()
                    {
                        FullName = model.FullName,
                        UserName = model.UserName,
                        EmailConfirmed = true,
                        PhoneNumber = model.PhoneNumber,
                        CardNumber = model.CardNumber,
                        ConfirmAccount = 1,
                        Email = model.Email,
                    };

                    if (model.Image != null)
                    {
                        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");

                        string[] allowedExtensions = { ".png", ".jpg", ".jpeg" };
                        if (!allowedExtensions.Contains(Path.GetExtension(model.Image.FileName).ToLower()))
                        {
                            TempData["ErrorMessage"] = "مسموح بالامتدادات التالية فقط .png و .jpg و .jpeg";
                            return RedirectToAction("Create");
                        }

                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        await using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await model.Image.CopyToAsync(fileStream);
                        }
                        user.ImageOfCard = uniqueFileName;
                    }

                    var result = await _userManager.CreateAsync(user, model.Password);

                    if (result.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(user, StaticDetails.Student);
                        await _context.SaveChangesAsync();
                        await _signInManager.SignOutAsync();

                        HttpContext.Session.SetString("created", "true");
                        return RedirectToAction("Index", "Home");
                    }
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var user = await _context.ApplicationUsers
                .FirstOrDefaultAsync(d => d.Id == id);

            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.user = user;

            if (user.ConfirmAccount == 2)
            {
                var editUserVM = new EditStudentVM
                {
                    Id = id,
                    FullName = user.FullName,
                    UserName = user.UserName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    CardNumber = user.CardNumber,
                };
                return View(editUserVM);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EditStudentVM editUserVM)
        {
            try
            {
                var user = await _context.ApplicationUsers
                   .FirstOrDefaultAsync(d => d.Id == id);
                if (user == null)
                {
                    await _signInManager.SignOutAsync();
                    return RedirectToAction("Index", "Home");
                }

                if (user.ConfirmAccount == 2)
                {
                    user.FullName = editUserVM.FullName;
                    user.UserName = editUserVM.UserName;
                    user.Email = editUserVM.Email;
                    user.PhoneNumber = editUserVM.PhoneNumber;
                    user.ConfirmAccount = 1;
                    user.CardNumber = editUserVM.CardNumber;

                    string oldImageFileName = user.ImageOfCard;
                    string Oldd = user.ImageOfCard;


                    if (editUserVM.Image != null)
                    {
                        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");

                        string[] allowedExtensions = { ".png", ".jpg", ".jpeg" };
                        if (!allowedExtensions.Contains(Path.GetExtension(editUserVM.Image.FileName).ToLower()))
                        {
                            TempData["ErrorMessage"] = "Only .png and .jpg and .jpeg images are allowed!";
                            return RedirectToAction("Edit");
                        }

                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + editUserVM.Image.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        await using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await editUserVM.Image.CopyToAsync(fileStream);
                        }

                        if (!string.IsNullOrEmpty(oldImageFileName))
                        {
                            string oldFilePath = Path.Combine(uploadsFolder, oldImageFileName);
                            if (System.IO.File.Exists(oldFilePath))
                            {
                                System.IO.File.Delete(oldFilePath);
                            }
                        }
                        user.ImageOfCard = uniqueFileName;
                    }
                    else
                    {
                        user.ImageOfCard = Oldd;
                    }

                    if (editUserVM.Password != null)
                    {
                        var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                        var result2 = await _userManager.ResetPasswordAsync(user, token, editUserVM.Password);
                        await _userManager.UpdateAsync(user);
                    }

                    _context.Update(user);
                    await _context.SaveChangesAsync();
                    HttpContext.Session.SetString("updated", "true");
                    await _signInManager.SignOutAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch
            {
                await _signInManager.SignOutAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(editUserVM);
        }
    
    }
}

ElmanhagPlatform/Controllers/StudentCoursesController.cs
using ElmanhagPlatform.Data;
using ElmanhagPlatform.Services;
using ElmanhagPlatform.Utility;
using ElmanhagPlatform.ViewModels.CourseDetails;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace ElmanhagPlatform.Controllers
{
    public class StudentCoursesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public StudentCoursesController(AppDbContext context, IWebHostEnvironment hostingEnvironment
            , UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Student(int courseId)
        {
            if (User.IsInRole("Teacher"))
            {
                if (HttpContext.Session.GetString("created") != null)
                {
                    ViewBag.created = true;
                    HttpContext.Session.Remove("created");
                }
                if (HttpContext.Session.GetString("updated") != null)
                {
                    ViewBag.updated = true;
                    HttpContext.Session.Remove("updated");
                }
                if (HttpContext.Session.GetString("deleted") != null)
                {
                    ViewBag.deleted = true;
                    HttpContext.Session.Remove("deleted");
                }

                var teacherId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                if (teacherId == null)
                    return RedirectToAction("Index", "Home");

                var course = await _context.Courses.FindAsync(courseId);

                if(course == null || course.TeacherId != teacherId)
                    return RedirectToAction("Index", "Home");

                ViewBag.Course = course;
                var users = await (from x in _context.ApplicationUsers
                                   join userRole in _context.UserRoles
                                   on x.Id equals userRole.UserId
                                   join role in _context.Roles
                                   on userRole.RoleId equals role.Id
                                   where role.Name == StaticDetails.Student
                                   && x.ConfirmAccount == 3
                                   && x.StudentCourses.Any(sc => sc.CourseId == courseId)
                                   select x)
                                .ToListAsync();

                return View(users);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        
        [HttpGet]
        public async Task<IActionResult> GetStudentCourseDetails(int id, string userId, int? videoId = null)
        {
            var sudtCourse = await _context.StudentCourses.Where(x => x.StudentId == userId && x.CourseId == id).FirstOrDefaultAsync();
            if (sudtCourse == null)
                return RedirectToAction("Index", "Home");

            var course = await _context.Courses
                                       .Include(c => c.Lectures)
                                       .ThenInclude(l => l.Videos)
                                       .Include(c => c.Lectures)
                                       .ThenInclude(l => l.PFiles)
                                       .Include(c => c.Lectures)
                                       .ThenInclude(l => l.Exams)
                                       .ThenInclude(d => d.Questions)
                                       .FirstOrDefaultAsync(c => c.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            var user = await _context.ApplicationUsers.FindAsync(userId);

            var watchLog = await _context.VideoWatchLogs
                   .Include(log => log.Video)
                   .ThenInclude(video => video.Lecture)
                   .Where(log => log.Video.Lecture.CourseId == id && log.UserId == userId)
                   .ToListAsync();
            ViewBag.Watchinglog = watchLog;

            var examSol = await _context.ExamAnswers
                           .Include(ans => ans.Exam)
                           .ThenInclude(ex => ex.Lecture)
                           .Include(ans => ans.Results)
                           .ThenInclude(res => res.Question)
                           .Where(ans => ans.Exam.Lecture.CourseId == id && ans.UserId == userId)
                           .ToListAsync();
            ViewBag.ExamesSol = examSol;

            var courseDetails = new CourseVM
            {
                teachId = course.TeacherId,
                Name = course.Name,
                Description = course.Description,
                CreationDate = course.CreationDate,
                UpdateDate = course.UpdateDate,
                Price = course.Price,
                Year = course.Year,
                ImageOfCourse = course.ImageOfCourse,
                VideosCount = course.Lectures.Sum(lec => lec.Videos.Count),
                FilesCount = course.Lectures.Sum(lec => lec.PFiles.Count),
                ExamsCount = course.Lectures.Sum(lec => lec.Exams.Count),
                LecturesVM = course.Lectures.Select(lec => new LectureVM
                {
                    Id = lec.Id,
                    Name = lec.Name,
                    Content = lec.Content,
                    VideosVM = lec.Videos.Select(v => new VideoVM
                    {
                        Id = v.Id,
                        Name = v.Name,
                        Description = v.Description,
                    }).ToList(),
                    PFilesVM = lec.PFiles.Select(f => new PFileVM
                    {
                        Id = f.Id,
                        Name = f.Name,
                        Description = f.Description,
                        FilePath = f.FilePath
                    }).ToList(),
                    ExamsVM = lec.Exams.Select(e => new ExamVM
                    {
                        Id = e.Id,
                        Name = e.Name,
                        Description = e.Description,
                        Duration = e.Duration,
                        Questions = e.Questions.ToList()
                    }).ToList()
                }).ToList()
            };

            return View(courseDetails);
        }


    }
}

ElmanhagPlatform/Views/StudentCourses/Student.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
@section Styles {
    <link rel="stylesheet" type="text/css" href="~/lib/table/datatable/datatables.css">
    <link rel="stylesheet" type="text/css" href="~/lib/table/datatable/dt-global_style.css">
    <link href="~/lib/toaster/toaster.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMvdL1eFiFmF5wN3K3jVrGzX+gY98/rFO7tB2kc" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
    <style>

        .cen {
            text-align: center;
        }

        .br-pagebody {
            margin-top: 20px;
        }

        .ri {
            text-align: left;
        }

        body {
            background-color: #f8f9fa;
            color: #343a40;
            font-family: 'Arial', sans-serif;
            direction: rtl;
            text-align: right;
        }

        .br-pagetitle h1 {
            color: #0066cc;
            font-size: 28px;
            font-weight: bold;
            text-align: center;
        }

        table {
            width: 100%;
            background-color: #ffffff;
            color: #333333;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

            table th, table td {
                padding: 12px;
                text-align: center;
                border-bottom: 1px solid #dee2e6;
            }

            table th {
                background-color: #f2f2f2;
                color: #333333;
            }

        .btn {
            padding: 8px 16px;
            font-size: 14px;
            border-radius: 4px;
        }

        .btn-secondary {
            background-color: #6c757d;
            color: #fff;
        }

        .btn-primary {
            color: #fff;
        }

        .btn-danger {
            background-color: #dc3545;
            color: #fff;
        }

        .btn-success {
            background-color: #28a745;
            color: #fff;
        }

        .image-receipt img {
            border-radius: 5px;
            max-width: 100px;
            max-height: 100px;
        }

        .autoo {
            height: auto;
        }

        .dataTables_filter {
            float: left !important;
        }

        .dataTables_wrapper .dataTables_filter input {
            height: 40px;
            font-size: 16px;
            padding: 5px 10px;
            border: 1px solid #ced4da;
            border-radius: 4px;
        }

        .dataTables_wrapper .dataTables_length {
            height: 50px;
            line-height: 50px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
        }

            .dataTables_wrapper .dataTables_length select {
                height: 40px;
                font-size: 16px;
                padding: 5px 10px;
                border: 1px solid #ced4da;
                border-radius: 4px;
            }

        .text-info {
            color: #17a2b8;
        }

        .modal-header {
            background-color: #ff9933;
            color: white;
        }

        .modal-body strong {
            color: #333333;
        }

        .size {
            font-size: 2rem;
            width: 50px;
            height: 50px;
            line-height: 1;
        }
    </style>
}

<div class="br-pagetitle page-margin-top">
    <div class="row align-items-center justify-content-center">
        <div class="col text-center">
            <h1>قائمة الطلاب المشتركين في كورس "@ViewBag.Course.Name"</h1>
        </div>
    </div>
</div>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        <div class="table-wrapper">
            <table id="deptsTable" class="table display responsive nowrap">
                <thead>
                    <tr>
                        <th>الهوية</th>
                        <th>اسم الطالب</th>
                        <th>رقم الهاتف</th>
                        <th>التفاصيل</th>
                        <th>النتائج</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @if (!string.IsNullOrEmpty(item.ImageOfCard))
                                {
                                    <div class="col">
                                        <a class="image-receipt" data-toggle="modal" data-target="#imageModal_@item.Id">
                                            <img src="~/images/@item.ImageOfCard" alt="صورة" width="50px" height="50px" />
                                        </a>
                                    </div>
                                    <div id="imageModal_@item.Id" class="modal fade" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <button type="button" class="close ri size" data-dismiss="modal" aria-label="اغلاق">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <div class="modal-body">
                                                    <img src="~/images/@item.ImageOfCard" alt="صورة كبيرة" class="img-fluid" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <span>لا توجد</span>
                                }
                            </td>
                            <td>@item.FullName</td>
                            <td>@item.UserName</td>
                            <td>
                                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#ModalUser_@item.Id">
                                    عرض
                                </button>
                            </td>
                            <td>
                                <a asp-action="GetStudentCourseDetails" asp-controller="StudentCourses" asp-route-userId="@item.Id" asp-route-id="@ViewBag.Course.Id" class="btn btn-primary text-white">
                                    <i class="fas fa-chart-line"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@foreach (var item in Model)
{
    <div class="modal fade" id="ModalUser_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title" id="exampleModalLabel">بيانات الطالب: @item.FullName</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="اغلاق">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3">
                        <div class="col">
                            <strong>اسم الطالب :</strong> <span class="text-info">@item.FullName</span>
                        </div>
                        <div class="col">
                            <strong>رقم الهاتف :</strong> <span class="text-info">@item.UserName</span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <strong>البريد الإلكتروني :</strong> <span class="text-info">@item.Email</span>
                        </div>
                        <div class="col">
                            <strong>رقم هاتف ولي الأمر :</strong> <span class="text-info">@item.PhoneNumber</span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <strong>الرقم القومي :</strong> <span class="text-info">@item.CardNumber</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">إغلاق</button>
                </div>
            </div>
        </div>
    </div>
}

@section scripts {
    @*     <partial name="_ValidationScriptsPartial" />
 *@
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="~/lib/table/datatable/datatables.js"></script>
    <script>
        $('#deptsTable').DataTable({
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "عدد النتائج   _TOTAL_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "بحث...",
                "sLengthMenu": "النتائج :  _MENU_ ",
            },
            "order": [[1, "desc"]],
            "stripeClasses": [],
            "lengthMenu": [7, 10, 20, 50, 100],
            "pageLength": 20,
            "scrollX": true,
            drawCallback: function () { $('.dataTables_paginate > .pagination').addClass(' pagination-style-13 pagination-bordered mb-5'); }
        });
    </script>
}